name: Cloud Infrastructure Common CI

on:
  push:
    branches:
      - 'feature/**'
    paths:
      - 'backend/cloud-infrastructure-common/**'
      - 'backend/domain-core/**'
      - 'backend/pom.xml'
  pull_request:
    branches: [ develop, master ]
    paths:
      - 'backend/cloud-infrastructure-common/**'
      - 'backend/domain-core/**'
      - 'backend/pom.xml'

permissions:
  contents: read
  pull-requests: write
  statuses: write

jobs:
  call-ci-workflow:
    uses: ./.github/workflows/reusable-ci.yml
    with:
      module_name: 'cloud-infrastructure-common'
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}